projects:

  js:a:
    root: ./js_a

  js:b:
    root: ./js_b

  php:a:
    root: ./php_a

scripts:

  deps:install:
    mode: series
    before_script: echo "Starting to install dependencies"
    script: echo "yarn install"
    after_script: echo "Return code from installation was ${IMBA_SCRIPT_RETURN_CODE}"
    projects:
      php:a:
        script: echo "composer install"

  run:dev:
    mode: series
    except: [js:b]
    environment:
      HOME: <parent.env.HOME>
      ENVIRONMENT: dev
    script:
      - env
      - date
      - exit 1    # let's fail here
      - uptime

  run:prod:
    mode: series
    only: [js:a]
    environment:
      ENVIRONMENT: prod
    dependencies:
      - deps:install
    script:
      - date
      - uptime

  work:
    mode: series
    script: echo "Working hard..."

  sleep:prepare:
    dependencies:
      - work
    before_script:
      - echo "Preparing to sleep on ${IMBA_PROJECT_NAME}"
    after_script:
      - echo "Prepared to sleep on ${IMBA_PROJECT_NAME}"
    script:
      - sleep 1

  sleep:
    dependencies:
      - sleep:prepare
    before_script:
      - echo "Before sleep on ${IMBA_PROJECT_NAME}"
    after_script:
      - echo "After sleep on ${IMBA_PROJECT_NAME}"
    script:
      - sleep 5
